spring.application.name=productos
# ===================================================================
# CONEXIÓN A ORACLE DATABASE
# ===================================================================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:ORCLCDB
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ===================================================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===================================================================
# Dialecto nativo para Oracle 12c Enterprise Edition
spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect

# 'validate' obliga a Hibernate a revisar si tu clase Producto.java coincide exactamente con DBeaver
spring.jpa.hibernate.ddl-auto=validate

# Muestra los queries formateados en la terminal para auditar
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
