-- Asegurar el esquema limpio de trabajo en Oracle
ALTER SESSION SET CURRENT_SCHEMA = C##RETO_TISMART;

-- 1. Creación de la Tabla Principal
CREATE TABLE producto (
    id_producto    NUMBER(10) GENERATED BY DEFAULT AS IDENTITY,
    codigo         VARCHAR2(20) NOT NULL,
    nombre         VARCHAR2(120) NOT NULL,
    marca          VARCHAR2(60) NOT NULL,
    modelo         VARCHAR2(60) NOT NULL,
    precio         NUMBER(10,2) NOT NULL,
    stock          NUMBER(10) NOT NULL,
    estado         CHAR(1) DEFAULT 'A' NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    fecha_modif    TIMESTAMP,
    
    -- Restricciones de integridad (Constraints)
    CONSTRAINT pk_producto PRIMARY KEY (id_producto),
    CONSTRAINT uk_producto_codigo UNIQUE (codigo),
    CONSTRAINT chk_producto_estado CHECK (estado IN ('A', 'I'))
);

-- 2. Crear el Índice Compuesto solicitado en el diagrama
CREATE INDEX idx_producto_marca_modelo ON producto (marca, modelo);

-- 3. Insertar 10 registros de prueba para poblar el listado inicial
INSERT INTO producto (codigo, nombre, marca, modelo, precio, stock, estado) 
VALUES ('PROD001', 'Smart TV 55 pulgadas 4K', 'Samsung', 'CU7000', 1899.00, 15, 'A');

INSERT INTO producto (codigo, nombre, marca, modelo, precio, stock, estado) 
VALUES ('PROD002', 'Laptop IdeaPad Slim 3', 'Lenovo', '15IAN8', 1499.50, 8, 'A');

INSERT INTO producto (codigo, nombre, marca, modelo, precio, stock, estado) 
VALUES ('PROD003', 'Smartphone Galaxy S24', 'Samsung', 'SM-S921B', 3499.00, 20, 'A');

INSERT INTO producto (codigo, nombre, marca, modelo, precio, stock, estado) 
VALUES ('PROD004', 'Audífonos Inalámbricos WH-CH520', 'Sony', 'WH-CH520', 199.00, 50, 'A');

INSERT INTO producto (codigo, nombre, marca, modelo, precio, stock, estado) 
VALUES ('PROD005', 'Monitor Gamer 24 pulg FHD', 'LG', '24GQ50F', 549.00, 12, 'A');

INSERT INTO producto (codigo, nombre, marca, modelo, precio, stock, estado) 
VALUES ('PROD006', 'Impresora Multifuncional EcoTank', 'Epson', 'L3250', 849.00, 0, 'I');

INSERT INTO producto (codigo, nombre, marca, modelo, precio, stock, estado) 
VALUES ('PROD007', 'Tablet MatePad SE 10.4', 'Huawei', 'AGS4-W09', 699.00, 25, 'A');

INSERT INTO producto (codigo, nombre, marca, modelo, precio, stock, estado) 
VALUES ('PROD008', 'Mouse Gamer Pro Wireless', 'Logitech', 'G-PPD-002WL', 429.90, 30, 'A');

INSERT INTO producto (codigo, nombre, marca, modelo, precio, stock, estado) 
VALUES ('PROD009', 'Teclado Mecánico Pop Keys', 'Logitech', '920-010717', 379.00, 5, 'A');

INSERT INTO producto (codigo, nombre, marca, modelo, precio, stock, estado) 
VALUES ('PROD010', 'Smartwatch Watch Fit 3', 'Huawei', 'PLO-B19', 499.00, 18, 'A');

-- Confirmar la transacción de inserciones en el disco de Oracle
COMMIT;